### PR TITLE
fix: resolve array access notice (fixes #2893)

### LINKED ISSUE #2893: Share Latest Export Files settings throw a PHP notice when no value is present in the database
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

If no value is present in the database for the "Share Latest Export Files" setting on the Sharing & Privacy page, the following PHP notices are displayed:

Screen shot showing error messages: 'Notice: Trying to access array offset on value of type bool in /srv/www/pressbooks.com/current/web/app/plugins/pressbooks/inc/admin/laf/namespace.php on line 1370' and 'Notice: Trying to access array offset on value of type bool in /srv/www/pressbooks.com/current/web/app/plugins/pressbooks/inc/admin/laf/namespace.php on line 1376'

### Steps to Reproduce

1. At the network level, allow users to share latest export files.
2. Create a new book.
3. Visit the book's sharing and privacy settings.

**Expected behavior:** No PHP notices appear.

**Actual behavior:** They appear as shown above.

#### Book Info

Book ID: 2
Book URL: http://pressbooks.test/mobydick/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Safari
Browser Version: 15.6
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.6 Safari/605.1.15

#### WordPress Configuration

Network URL: http://pressbooks.test/
Network Type: Subdirectory
Version: 6.0.1
Language: en_US
WP_ENV: development
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.36.1
Book Theme: McLuhan
Book Theme Version: 2.18.2
Root Theme: Aldine
Root Theme Version: 1.15.0-dev

#### Pressbooks Dependencies

Epubcheck: Not Installed
xmllint: Not Installed
PrinceXML: Not Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

Bedrock Autoloader: 1.0.3
hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 5.36.1

#### Book Active Plugins

Pressbooks: 5.36.1

#### Server Configuration

PHP Version: 7.4.30
MySQL Version: 5.5.5
Webserver Info: nginx/1.23.1

#### PHP Configuration

Memory Limit: 256M
Upload Max Size: 25M
Post Max Size: 25M
Upload Max Filesize: 25M
Time Limit: 120
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: On (1)

#### PHP Extensions

OPcache: Zend
XDebug: Enabled
cURL: Supported
cURL Version: 7.68.0
imagick: Installed
xsl: Installed

### PR DESCRIPTION
**Pull request by greatislander**
Fix for #2893

### CODE REVIEW

File: inc/admin/laf/namespace.php [hunk 1]
```diff
@@ -1365,15 +1365,15 @@ function privacy_disable_comments_callback( $args ) {
  * @param $args
  */
 function privacy_latest_files_public_callback( $args ) {
-	$blog_public = get_option( 'pbt_redistribute_settings' );
+	$blog_public = get_option( 'pbt_redistribute_settings', [] );
 	$html = '<input type="radio" id="latest_files_public" name="pbt_redistribute_settings[latest_files_public]" value="1" ';
-	if ( $blog_public['latest_files_public'] ) {
+	if ( isset($blog_public['latest_files_public']) && $blog_public['latest_files_public'] === 1 ) {
```
Comment (SteelWagstaff) [inline inc/admin/laf/namespace.php:1370]:
```suggestion
	if ( isset( $blog_public['latest_files_public'] ) && $blog_public['latest_files_public'] === 1 ) {
```

File: inc/admin/laf/namespace.php [hunk 2]
```diff
@@ -1365,15 +1365,15 @@ function privacy_disable_comments_callback( $args ) {
...
 		$html .= 'checked="checked" ';
 	}
 	$html .= '/>';
 	$html .= '<label for="latest_files_public"> ' . __( 'Yes. I would like the latest export files to be available on the homepage for free, to everyone.', 'pressbooks' ) . '</label><br />';
 	$html .= '<input type="radio" id="latest_files_private" name="pbt_redistribute_settings[latest_files_public]" value="0" ';
-	if ( ! $blog_public['latest_files_public'] ) {
+	if ( ! isset($blog_public['latest_files_public']) || $blog_public['latest_files_public'] === 0 ) {
```
Comment (SteelWagstaff) [inline inc/admin/laf/namespace.php:1376]:
```suggestion
	if ( ! isset( $blog_public['latest_files_public'] ) || $blog_public['latest_files_public'] === 0 ) {
```

**Review by SteelWagstaff — APPROVED** [review]
LGTM. Thanks Ned!
