### PR TITLE
Fix web paragraph separation bug, for real (closes #1303)

### LINKED ISSUE #1303: When switching themes, the line separation property is reset
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

This property should not change when switching themes.

### Steps to Reproduce

1. Set the line separation theme option to skip lines.
2. Switch themes.

**Expected behavior:** User setting is preserved.

**Actual behavior:** User setting is not preserved.

### System Information

Pressbooks: 5.4.3
McLuhan: 2.4.2

### PR DESCRIPTION
**Pull request by greatislander**
This PR fixes three issues I found that were causing paragraph separation to fall back to indent for editor and web stylesheets.

- [x] Using the variable `$sass` for both an instance of `\Leafo\ScssPhp\Compiler` and an instance of `\Pressbooks\Sass` was causing conflicts between identically-named `setVariables()` methods in these classes.
- [x] Adding `\Pressbooks\Modules\ThemeOptions\WebOptions::scssOverrides` to the `pb_web_css_override` filter hook in `hooks-admin.php` meant that regeneration of the web stylesheet triggered by a visit to the webbook would not apply theme options overrides.
- [x] Looking up the webbook theme version with a default value of `$current_theme_version` meant that the `version_compare()` check would always show that nothing had changed (unless Buckram was updated).

### CODE REVIEW

File: inc/class-styles.php [hunk 1]
```diff
@@ -572,17 +575,18 @@ public function maybeUpdateStylesheets() {
 		// Theme was updated?
 		$theme = wp_get_theme();
 		$current_theme_version = $theme->get( 'Version' );
-		$last_theme_version = get_option( 'pressbooks_theme_version', $current_theme_version );
+		$last_theme_version = get_option( 'pressbooks_theme_version', 0 );
```
Comment (connerbw) [inline inc/class-styles.php]: Is this a  leftover from testing or on purpose?

File: inc/class-styles.php [hunk 2]
```diff
@@ -572,17 +575,18 @@ public function maybeUpdateStylesheets() {
...
 			$this->updateWebBookStyleSheet();
+			update_editor_style();
 			update_option( 'pressbooks_theme_version', $current_theme_version );
 			return true;
 		}
 
 		// Buckram was updated?
 		$current_buckram_version = $this->getBuckramVersion();
-		$last_buckram_version = get_option( 'pressbooks_buckram_version', '0.1.0' );
+		$last_buckram_version = get_option( 'pressbooks_buckram_version', 0 );
```
Comment (connerbw) [inline inc/class-styles.php]: Is this a  leftover from testing or on purpose?

File: inc/class-styles.php (hunk 1 above)
Comment (greatislander) [reply inc/class-styles.php]: On purpose. I found that this was happening:

```
$current_theme_version = 1.1.0;
$last_theme_version = get_option( 'pressbooks_theme_version', $current_theme_version ); // If no option set, returns 1.1.0
```

Then `version_compare()` always shows that the theme hasn't been updated, never saves a version in the options table.

File: inc/class-styles.php [hunk 3]
```diff
@@ -575,8 +575,9 @@ public function maybeUpdateStylesheets() {
 		// Theme was updated?
 		$theme = wp_get_theme();
 		$current_theme_version = $theme->get( 'Version' );
-		$last_theme_version = get_option( 'pressbooks_theme_version', 0 );
+		$last_theme_version = get_option( 'pressbooks_theme_version' );
 		if ( version_compare( $current_theme_version, $last_theme_version ) > 0 ) {
+			xdebug_break();
```
Comment (connerbw) [inline inc/class-styles.php]: phpcs don't fail me now?
