### PR TITLE
Fix stylesheet rebuild stampede (closes #1383)

### LINKED ISSUE #1383: Prevent cache stampede when regenerating stylesheets
### Prerequisites

* [x] Can you reproduce the behavior you wish to address with [all other plugins deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x] Are you experiencing this issue with one of our built-in root or book themes?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks) to see if your bug or enhancement is already listed?

### Description

On high-traffic books, when the theme is updated, visits my prompt a cache stampede as the stylesheet is regenerated. We should prevent additional requests to regenerate the stylesheet using a transient that expires in 5 minutes to rate limit this action.

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 5.5.2

### PR DESCRIPTION
**Pull request by greatislander**

### CODE REVIEW

File: inc/class-styles.php [hunk 1]
```diff
@@ -574,27 +574,32 @@ public function maybeUpdateStylesheets() {
...
+				set_transient( 'pressbooks_updating_stylesheet', 1, 5 * MINUTE_IN_SECONDS );
+				( new ThemeOptions() )->clearCache();
+				$this->updateWebBookStyleSheet();
+				update_editor_style();
+				if ( $buckram_updated ) {
+					update_option( 'pressbooks_buckram_version', $current_buckram_version );
+				}
+				if ( $theme_updated ) {
+					update_option( 'pressbooks_theme_version', $current_theme_version );
+				}
```
Comment (connerbw) [inline inc/class-styles.php]: `delete_transient( 'pressbooks_updating_stylesheet' );`

Then, return true.
