### PR TITLE
Privacy policy management

### LINKED ISSUE #1235: Add support for WordPress GDPR tools
### Description

WordPress core GDPR (privacy) tools should work within Pressbooks. This requires:

- [x] Add Pressbooks-specific text to the privacy policy guide page
- [x] Ensure that the privacy settings page is available to administrators of the network home page (see pressbooks/pressbooks-aldine#129)
- [x] Hide the privacy settings page from individual books
- [x] Add support for exporting personal data stored by Pressbooks
- [x] Add support for erasing personal data stored by Pressbooks

### Steps to Reproduce

Not applicable.

### System Information

Pressbooks: 5.4.0-dev

### PR DESCRIPTION
**Pull request by greatislander**
- [x] Hide the privacy settings page from individual books

Partially addresses #1235.

### CODE REVIEW

File: inc/admin/privacy/namespace.php [hunk 1]
```diff
@@ -0,0 +1,26 @@
...
+ * @see https://developer.wordpress.org/plugins/privacy/suggesting-text-for-the-site-privacy-policy/
+ *
+ * @since 5.4.0
+ */
+function add_privacy_policy_content() {
+	if ( ! function_exists( 'wp_add_privacy_policy_content' ) ) {
+		return;
+	}
+
+	$content = __( 'TODO.', 'pressbooks' );
```
Comment (greatislander) [inline inc/admin/privacy/namespace.php]: This needs to be written.
